before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: KnOcBbTf0+HtTrF1lIEs3eOgRs0tMnEcogoHy45pPABTzrPcjAoklcI8+4VO7Q9zgYh40KQ/zVnpihVBlSc/+aK4lV9HVL37+TxeSF+/9A54vQUxoxAedc7iRt59OGl+6o6UhiGiPCjSNYXYh+Q4bHArXLamL454vaCNeyWxj3/7KcKf9SgpxIgmWR3GLuCbxON6j7K65EaOT99F56cdzLarSP/WC/KqWX3F8XV4kqh7fnELpko2Z3+dc5+xt9DNX94syeZnPABBprb15UPX8pD16tB727G7ovvNcPIcdGNULbAEMfRafiPvVC9Qj9r9fcogbgiubj5Ntzn5Jt9YFIMAixPViCbmAkpRjTpAatOFO1TReHdYdn4aJRIikhCYPzebj5qXfcdvr9duod6hhJqLTKOdmS+ByprZFMbBbAnsekgDLQo5ztKFd57YPXL23eCQMcLCEz68F1Tb4E7af43YZHc92fgQfwyRBIguD6l3BuwD/A56lZEV//2DVKDka9Em3YRL0jqHBfjQGUbVGTdC5uH8Bah0J9Xn/FBQZ9wPmXAnI6H/P6yKsLNw1YbzahJcvG9o6j4iYrGdVbVPS9J1xzJ8i57kpCRAURfXeBFateYdYAKL3WjhRyXukUQqNhkUDkmWBVlseYAJK0iMdTgBMwRexFzBhaRO3+FPUPY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
